### ISSUE TITLE
Uncaught type error after adding files for upload

### ISSUE THREAD

**Issue by ccesarz** [Kloudless/file-picker#90] opened 2019-11-06 16:21 UTC
**Steps to reproduce**
1. Select “My Computer” from the Kloudless icon menu.
2. When the add files modal appears, click the drop-down button on the top left, which has "My Computer" selected, to show the drop-down menu items.
3. Select the same drop-down menu item as selected, which is “My Computer” in this case.
4. Click the “Add Files” button.
5. Select one or more files and click the “Open” button.

**Result**

The expected result does not occur and further actions to add files fail.  The console shows the following error:
explorer.js:116 Uncaught TypeError: Cannot read property 'test' of undefined
    at o.Uploader.<anonymous> (explorer.js:116)
    at Array.<anonymous> (explorer.js:116)
    at r (explorer.js:83)
    at explorer.js:83
    at explorer.js:116
    at o.Uploader.<anonymous> (explorer.js:116)
    at Array.<anonymous> (explorer.js:116)
    at r (explorer.js:83)
    at explorer.js:83
    at explorer.js:116

**Comment by pseudonumos** [comment] 2019-11-06 21:04
Thanks for reaching out! We've tracked this internally and will let you know when we have a fix available.

**Comment by hong19** [comment] 2019-11-14 07:26
Hi @ccesarz, I couldn't reproduce this error. 
Could you provide the config options? 
for example:
```javascript
const FILE_CHOOSER_OPTIONS = {
    name: 'File Chooser',
    elementId: 'file-chooser',
    objId: 'fileChooser',
    explorerOptions: {
      multiselect: true,
      link: false,
      computer: true,
      services: ['all'],
      types: ['all'],
      display_backdrop: true
    },
  };
```

**Comment by vinodc** [comment] 2020-06-06 06:17
We're unable to reproduce this error so are closing the ticket. Our latest release also contains significant updates to this logic.

**Closed by vinodc** 2020-06-06 06:17 UTC
