### ISSUE TITLE
Cancel button transmogrified following upload in Safari

### ISSUE THREAD

**Issue by ccesarz** [Kloudless/file-picker#92] opened 2019-11-08 18:51 UTC
**Steps to reproduce:**

1. Load the explorer in Safari
2. Choose "My Computer" as service type
3. Click "Add Files"
4. Choose a file and click upload
5. Revisit the modal where files can be chosen.
6. Notice the cancel button's height and the upload button's width are reduced.

<img width="715" alt="Screen Shot 2019-11-08 at 1 45 46 PM" src="https://user-images.githubusercontent.com/21110554/68502630-e3186780-022e-11ea-80a5-25c2594bbcaa.png">

**Comment by hong19** [comment] 2019-11-15 06:36
Hi @ccesarz, I couldn't reproduce this error. 
I have some questions to clarify the conditions:
After the step 4 click `upload`, the it start to upload the file. In this step, we should wait for the upload completing? 
After the upload completed. The file-explorer will be closed. Step 5 `Revisit the modal where files can be chosen.` means re-launch the file-explorer?

**Comment by vinodc** [comment] 2020-06-06 06:20
Our latest release redoes this UI entirely, so we're closing this ticket.

**Closed by vinodc** 2020-06-06 06:20 UTC
